package uacj.mx.app08_appra.ui.controladores

import kotlinx.serialization.Serializable

@Serializable
object OpcionNavegacionPantallaPrincipal

@Serializable
object OpcionNavegacionPantallaPistasInformacion

@Serializable
object OpcionNavegacionPantallaPistasInteractivo

@Serializable
object OpcionNavegacionPantallaPistasCamara

@Serializable
object OpcionNavegacionPantallaPistasAgitarTelefono